SustainableCityManagement/SCM/urls.py
from django.urls import path
from SCM.views import (
    login_view,
    ValidateLoginView,
    DisplayMapView,
    DisplayPollutionData,
    DisplayDublinBusData,
    DisplayEventsData,
    DisplayDublinBikesData,
    push_notify
    )

app_name = "SCM"
urlpatterns = [
    path('Home/', ValidateLoginView, name='validate-login'),
    path('Traffic/', DisplayMapView, name='traffic-data'),
    path('PollutionData/', DisplayPollutionData, name='pollution-data'),
    path('DublinBus/', DisplayDublinBusData, name='bus-data'),
    path('Events/', DisplayEventsData, name='event-data'),
    path('DublinBikes/',DisplayDublinBikesData, name='bikes-data'),
    path('PushNotification/', push_notify, name='push-notification')


]

SustainableCityManagement/SustainableCityManagement/urls.py
# Uncomment next two lines to enable admin:
#from django.contrib import admin
from django.urls import include, path
from SCM.views import login_view

urlpatterns = [
    # Uncomment the next line to enable the admin:
    #path('admin/', admin.site.urls)
    path('SCM/' , include('SCM.urls')),
    path('', login_view, name='login')

]

SustainableCityManagement/SCM/models.py
from django.db import models

# Create your models here.
class UserDetails(models.Model):
    userName = models.CharField(max_length = 15,primary_key=True)
    Password = models.CharField(max_length = 30)
    userRole = models.CharField(max_length = 15)

SustainableCityManagement/SCM/forms.py
from django import forms
from .models import UserDetails


class UserLoginForm(forms.ModelForm):
    userName = forms.CharField(widget = forms.TextInput(attrs={"placeholder":"Username", "class":"form-control"}))
    password = forms.CharField(widget = forms.PasswordInput(attrs={"placeholder":"Password", "class":"form-control"}))  

    class Meta:
        model = UserDetails
        fields = [
            'userName',
            'password'
            ]    

        
        

SustainableCityManagement/SCM/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import UserDetails
from .forms import UserLoginForm
from django.core.paginator import Paginator
import requests
# Create your views here.
def login_view(request):
    form = UserLoginForm(request.POST or None)        
    context = {
        'form': form
        }

    return render(request, "login.html", context)

def ValidateLoginView(request):
    userName = request.POST['userName']
    password = request.POST['password']
    userLoginDetails = UserDetails.objects.filter(userName = userName, Password = password)
    if userLoginDetails:
        response = requests.get('http://erc.epa.ie/real-time-air/www/aqindex/aqih_json.php')
        pollution = response.json()
        dict1 = dict()
        for i in range(0, len(pollution['aqihsummary'])):
            if '_' in pollution['aqihsummary'][i]['aqih-region']:
                region = pollution['aqihsummary'][i]['aqih-region'].split('_')[0] + " " + pollution['aqihsummary'][i]['aqih-region'].split('_')[1]
            else:
                region = pollution['aqihsummary'][i]['aqih-region']
            dict1[region] = pollution['aqihsummary'][i]['aqih']
        
        context = {
            "data" : dict1
            }
        return render(request, "pollution.html", context)    
    else:
        return HttpResponse("Invalid username or password.")

def DisplayMapView(request):
    return render(request,"TrafficMap.html",{})


def DisplayPollutionData(request):
    response = requests.get('http://erc.epa.ie/real-time-air/www/aqindex/aqih_json.php')
    pollution = response.json()
    dict1 = dict()
    for i in range(0, len(pollution['aqihsummary'])):
        if '_' in pollution['aqihsummary'][i]['aqih-region']:
            region = pollution['aqihsummary'][i]['aqih-region'].split('_')[0] + " " + pollution['aqihsummary'][i]['aqih-region'].split('_')[1]
        else:
            region = pollution['aqihsummary'][i]['aqih-region']
        dict1[region] = pollution['aqihsummary'][i]['aqih']
        
    context = {
        "data" : dict1
        }
    return render(request, "pollution.html", context)

def DisplayDublinBusData(request):
    response = requests.get('https://data.dublinked.ie/cgi-bin/rtpi/routelistinformation')
    dublinbus=response.json()
    
    
    page= request.GET.get('page',1)
    paginator = Paginator(dublinbus['results'], 20)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {
        "data": data
        }    
    return render(request,"BusRouteInfo.html",context)

def DisplayEventsData(request):
    
    response = requests.get('https://app.ticketmaster.com/discovery/v2/events.json?countryCode=IE&apikey=u2MCIW0dPwxqAZMCssL2PrGWWfdkGedj')
    events=response.json()
    dict1 = dict()
    for i in range(0 , len(events['_embedded']['events'])):
        
        dict1[events['_embedded']['events'][i]['id']] = {'name':events['_embedded']['events'][i]['name'],
                                                        'dateTime': events['_embedded']['events'][i]['dates']['start']['localTime'] + " " + 
                                                        events['_embedded']['events'][i]['dates']['start']['localDate'],
                                                        'location': "Latitude - " + events['_embedded']['events'][i]['_embedded']['venues'][0]['location']['latitude'] + " " +
                                                        "Longitude - " + events['_embedded']['events'][i]['_embedded']['venues'][0]['location']['longitude']
                                                        
                                                         }
                                                        

    context = {
        "data" : dict1
        }
    return render(request,"events.html",context)


def DisplayDublinBikesData(request):
    response= requests.get(' https://api.jcdecaux.com/vls/v1/stations?contract=dublin&apiKey=77cf7ab00377c7f4cc621765273db0e7daf18f82')
    dublinbikes=response.json()

    page= request.GET.get('page',1)
    paginator = Paginator(dublinbikes, 20)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    context = {
        "data" : data
        }
    return render(request,"dublinbikes.html", context)


def push_notify(request):
    from pusher_push_notifications import PushNotifications

    beams_client = PushNotifications(
        instance_id='422713b7-8870-499a-8534-5553787dc86c',
         secret_key='6DACD3113B8FF98826AB73E91EB1BF4EADC216BBB8567B562A065F4BD1E71C60',
    )
    response = beams_client.publish_to_interests(
    interests=['hello'],
    publish_body={
        'apns': {
            'aps': {
                'alert': 'Notification form Dashboard!'
            }
        },
        'fcm': {
            'notification': {
                'title': 'Notification from Dashboard!',
                'body': 'Notification from Dashboard!'
            }
        }
    }
    )

    return HttpResponse('Notification Sent')


    

SustainableCityManagement/SCM/templates/SCM/BusRouteInfo.html
{% extends 'dashboard.html' %}
{% load static %}
{% block static_file %}
    <link rel="stylesheet" href="{% static 'nav.css' %}">
{% endblock %}
{% block content %}
    <table style="margin:10px">
        <tr>
            <th>Operator</th>
            <th>Operator Type</th>
            <th>Route</th>
        </tr>
        {% for item in data %}
            <tr>            
                <td>{{item.operator}}</td>
                <td>{{item.operatortype}}</td>
                <td>{{item.route}}</td>
            </tr>
        {% endfor %}
    </table>

    {% if data.has_other_pages %}
  <ul class="pagination">
    {% if data.has_previous %}
      <li><a href="?page={{ data.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in data.paginator.page_range %}
      {% if data.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if data.has_next %}
      <li><a href="?page={{ data.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

SustainableCityManagement/SCM/templates/SCM/TrafficMap.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <title>Traffic Layer</title>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      button:hover {
        border: 1px solid white;
        }
    </style>
  </head>
  <body>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Sustainable City Management</a>
        <form method="get" action="{% url 'SCM:pollution-data' %}">
            <button class="btn" style="color:white">Pollution data</button>
        </form>
        <form method="get" action="{% url 'SCM:bikes-data' %}">
            <button class="btn" style="color:white">Dublin Bikes data</button>
        </form>
        <form method="get" action="{% url 'SCM:traffic-data' %}">
            <button class="btn" style="color:white">Traffic map</button>
        </form>        
        <form method="get" action="{% url 'SCM:bus-data' %}">
            <button class="btn" style="color:white">Dublin Bus data</button>
        </form>
        <form method="get" action="{% url 'SCM:event-data' %}">
            <button class="btn" style="color:white">Events data</button>
        </form>             
        <form method="get" action="{% url 'SCM:push-notification' %}">
            <button class="btn" style="color:white">
                Send Notification
            </button>
        </form>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>       
  
      </nav>
      <div style="margin:5px">
	    <label for="lat">Latitude</label>
	    <input type="text" class="form-control" style="width:140px" id="lat">
      </div>
      <div style="margin:5px">
	    <label for="long">Longitude</label>
	    <input type="text" class="form-control" style="width:140px" id="long">
      </div>
      <div style="margin:5px">
	    <button type="submit" class="btn btn-primary" onclick="javascript:initMap()">View Map</button>
      </div>
      <div id="map"></div>

      <script async defer>
      function initMap() {
          var lati = document.getElementById('lat').value
          var long = document.getElementById('long').value

          if (!lati && !long) {
             var map = new google.maps.Map(document.getElementById('map'), {
                 zoom: 13,
                 center: { lat: parseFloat(lati), lng: parseFloat(long) }
			});
			var trafficLayer = new google.maps.TrafficLayer();
			trafficLayer.setMap(map);
          }
          else {
            var map = new google.maps.Map(document.getElementById('map'), {
			zoom: 13,
			center: {lat: 53.2734, lng: -7.77832031}
			});
			var trafficLayer = new google.maps.TrafficLayer();
			trafficLayer.setMap(map);
          }
		
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlqp_xDwz-gGxa4BfprQ_cyl98Obgdc6w&callback=initMap">
    </script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  </body>
</html>

SustainableCityManagement/SCM/templates/SCM/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block login_css %}
    {% endblock %}
    <style>
        table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
        }
    </style>
  </head>
  <body style="background-color:aliceblue">
      {% include 'navbar.html' %}
      {% block content %}
      {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

SustainableCityManagement/SCM/templates/SCM/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <form method="get" action="{% url 'SCM:traffic-data' %}">
        <button class="btn" style="margin:5px; border:1px solid black">View traffic map</button>
    </form>
    <form method="get" action="{% url 'SCM:pollution-data' %}">
        <button class="btn" style="margin:5px; border:1px solid black">View pollution data</button>
    </form>
    <form method="get" action="{% url 'SCM:bus-data' %}">
        <button class="btn" style="margin:5px; border:1px solid black">View Dublin Bus data</button>
    </form>
    <form method="get" action="{% url 'SCM:event-data' %}">
        <button class="btn" style="margin:5px; border:1px solid black">View events data</button>
    </form>
    <form method="get" action="{% url 'SCM:bikes-data' %}">
        <button class="btn" style="margin:5px; border:1px solid black">View Dublin Bikes data</button>
    </form>     
    <form method="get" action="{% url 'SCM:push-notification' %}">
        <button class="btn" style="margin:5px; border:1px solid black">
            Send Notification
        </button>
    </form>
{% endblock %}

SustainableCityManagement/SCM/templates/SCM/dublinbikes.html
{% extends 'dashboard.html' %}
{% load static %}
{% block static_file %}
    <link rel="stylesheet" href="{% static 'nav.css' %}">
{% endblock %}
{% block content %}
    <table style="margin:10px">
        <tr>
            <th>Address</th>
            <th>Longitude</th>
            <th>Latitude</th>
            <th>Available Bike Stands</th>
            <th>Available Bikes</th>
            <th>Contract Name</th>
            <th>Name</th>
            <th>Number</th>        
            <th>Status</th>
        </tr>
        
        {% for item in data %}
            <tr>
                <td>{{item.address}}</td>
                <td>{{item.position.lng}}</td>
                <td>{{item.position.lat}}</td>
                <td>{{item.available_bike_stands}}</td>
                <td>{{item.available_bikes}}</td>
                <td>{{item.contract_name}}</td>
                <td>{{item.name}}</td>
                <td>{{item.number}}</td>
                <td>{{item.status}}</td>
            </tr>
        {% endfor %}
    </table>
{% if data.has_other_pages %}
  <ul class="pagination" style="border:1px solid black; margin:10px;">
    {% if data.has_previous %}
      <li><a href="?page={{ data.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in data.paginator.page_range %}
      {% if data.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if data.has_next %}
      <li><a href="?page={{ data.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

SustainableCityManagement/SCM/templates/SCM/dublinbus.html
{% extends 'base.html '%}
{% block content %}
{% for x in data.items %}
    <p>{{x}}</p>
{% endfor %}
{% endblock %}

SustainableCityManagement/SCM/templates/SCM/event.html
{% extends 'base.html '%}
{% block content %}
{% for x in data.items %}
    <p>{{x}}</p>
{% endfor %}
{% endblock %}

SustainableCityManagement/SCM/templates/SCM/events.html
{% extends 'dashboard.html' %}
{% load static %}
{% block static_file %}
    <link rel="stylesheet" href="{% static 'nav.css' %}">
{% endblock %}
{% block content %}
    <table style="margin:10px">
        <tr>
            <th>Event Name</th>
            <th>Event Date and Time</th>            
            <th>Event Location</th>
        </tr>
        {% for key, value in data.items %}
            <tr>            
                <td>{{value.name}}</td>
                <td>{{value.dateTime}}</td>
                <td>{{value.location}}</td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

SustainableCityManagement/SCM/templates/SCM/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="row" style="margin-top:115px; height:300px">
        <div class="col-4"></div>
        <div class="col-4" style="border:2px solid black; background-color:white;" >
            <div class="row">
                <div class="col-4"></div>
                <div class="col-4" style="margin:20px 0 20px 0">
                    <h5>SCM Login</h5>
                </div>
                <div class="col-4"></div>
            </div>
            <div class="row">
                <div class="col-12">
                    <form method="post" action="{% url 'SCM:validate-login' %}">
                        {% csrf_token %}
                        <div style="margin:10px;" class="form-group">
                            {{form.userName}}
                        </div>
                        <div style="margin:10px;" class="form-group">
                            {{form.password}}
                        </div>
                        <button class="btn btn-primary" style="margin:10px; width:410px" name="btn_login">Sign in</button>            
                    </form>
                </div>
            </div>
            
        </div>
        <div class="col-4"></div>
    </div>
    
{% endblock %}

SustainableCityManagement/SCM/templates/SCM/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-top:-25px">
  <a class="navbar-brand" href="#">Sustainable City Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>  
</nav>

SustainableCityManagement/SCM/templates/SCM/pollution.html
{% extends 'dashboard.html' %}
{% load static %}
{% block static_file %}
    <link rel="stylesheet" href="{% static 'nav.css' %}">
{% endblock %}
{% block content %}
{% for key, value in data.items %}
    <p>{{key}} - {{value}}</p>
{% endfor %}
{% endblock %}